name: Say Hello
run-name: ${{ github.actor }} is testing GitHub Actions ðŸš€
on: [push]
jobs:
  Say-Hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Hello World
        run: |
          echo hello world!
      - run: echo "This job's status is ${{ job.status }}."
